# Generated by Django 3.2.7 on 2021-09-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0002_auto_20210908_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastUpdated',
            field=models.CharField(default='', max_length=100),
        ),
    ]
