# Generated by Django 3.2.7 on 2021-09-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0004_repositories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositories',
            name='user',
        ),
        migrations.AddField(
            model_name='repositories',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
